FROM node:latest as frontendbuilder
WORKDIR /app

COPY services/frontend/package.json services/frontend/package-lock.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm ci

COPY services/frontend .
RUN npm run build

# ---------------------------------------------------
FROM nginx:latest 
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*
COPY --from=frontendbuilder /app/dist .
