run:
  timeout: 5m
  tests: true
  skip-dirs:
    - swagger-docs
    - bin
    - dist

linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - gosec
    - misspell
    - goimports
    - revive
    - gocritic
    - gofumpt

  disable:
    - godot
    - godox
    - testpackage
    - wsl
    - nlreturn
    - gochecknoinits
    - gochecknoglobals
    - funlen

linters-settings:
  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  govet:
    check-shadowing: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec

    - path: src/migrator/
      linters:
        - dupl

    - path: src/cmd/
      linters:
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number