package configuration

var (
	// WEBSERVER
	WEBSERVER_DISPLAYNAME   = GetEnvOrDefaultString("WEBSERVER_DISPLAYHOST", "http://web.localhost/")
	WEBSERVER_HOST          = GetEnvOrDefaultString("WEBSERVER_HOST", "127.0.0.1")
	WEBSERVER_PORT          = GetEnvOrDefaultInt("WEBSERVER_PORT", 3000)
	WEBSERVER_SHOW_FRONTEND = GetEnvOrDefaultBool("WEBSERVER_SHOW_FRONTEND", true)
	WEBSERVER_SHOW_SWAGGER  = GetEnvOrDefaultBool("WEBSERVER_SHOW_SWAGGER", true)

	// Database
	// DATABASE_ADDR = GetEnvOrDefaultString("DATABASE_ADDR", "127.0.0.1")
	DATABASE_ADDR     = GetEnvOrDefaultString("DATABASE_ADDR", "postgres")
	DATABASE_PORT     = GetEnvOrDefaultInt("DATABASE_PORT", 5432)
	DATABASE_SSL      = GetEnvOrDefaultBool("DATABASE_SSL", false)
	DATABASE_USERNAME = GetEnvOrDefaultString("DATABASE_USERNAME", "postgres")
	DATABASE_PASSWORD = GetEnvOrDefaultString("DATABASE_PASSWORD", "postgres")
	DATABASE_DATABASE = GetEnvOrDefaultString("DATABASE_DATABASE", "postgres")

	// JWT
	JWT_TOKEN_VALIDITY_IN_MINUTES  = GetEnvOrDefaultInt("JWT_TOKEN_VALIDITY_MINS", 15)
	REFRESH_TOKEN_VALIDITY_IN_DAYS = GetEnvOrDefaultInt("REFRESH_TOKEM_VALIDITY_MINS", 30)
	JWT_SIGNING_KEY                = GetEnvOrDefaultString("JWT_SIGNING_KEY", "qWeRtZ12345")
	REFRESH_TOKEN_SIGNING_KEY      = GetEnvOrDefaultString("JWT_SIGNING_KEY", "qWeRtZ12345")

	// Oauth
	AUTHORIZATION_OAUTH_AUTHENTIK                   = GetEnvOrDefaultBool("AUTHORIZATION_OAUTH_AUTHENTIK", true)
	AUTHORIZATION_OAUTH_AUTHENTIK_KEY               = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_CLIENT_KEY", "")
	AUTHORIZATION_OAUTH_AUTHENTIK_SECRET            = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_CLIENT_SECRET", "")
	AUTHORIZATION_OAUTH_AUTHENTIK_CALLBACK_URL      = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_REDIRECT_URL", "http://web.localhost/api/v1/callback")
	AUTHORIZATION_OAUTH_AUTHENTIK_AUTHORIZATION_URL = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_AUTHORIZATION_URL", "http://localhost:9000/application/o/authorize/")
	AUTHORIZATION_OAUTH_AUTHENTIK_TOKEN_URL         = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_TOKEN_URL", "")
	AUTHORIZATION_OAUTH_AUTHENTIK_USERINFO_URL      = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_USERINFO_URL", "")
	AUTHORIZATION_OAUTH_AUTHENTIK_SCOPES            = GetEnvOrDefaultStringArray("AUTHORIZATION_OAUTH_AUTHENTIK_SCOPES", []string{})
	AUTHORIZATION_OAUTH_AUTHENTIK_LOGOUT_URL        = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHENTIK_LOGOUT_URL", "")
)
