package configuration

var (
	// WEBSERVER
	WEBSERVER_DISPLAYNAME   = GetEnvOrDefaultString("WEBSERVER_DISPLAYHOST", "http://web.localhost/")
	WEBSERVER_HOST          = GetEnvOrDefaultString("WEBSERVER_HOST", "127.0.0.1")
	WEBSERVER_PORT          = GetEnvOrDefaultInt("WEBSERVER_PORT", 443)
	WEBSERVER_SHOW_FRONTEND = GetEnvOrDefaultBool("WEBSERVER_SHOW_FRONTEND", true)
	WEBSERVER_SHOW_SWAGGER  = GetEnvOrDefaultBool("WEBSERVER_SHOW_SWAGGER", true)

	// Database
	// DATABASE_ADDR = configurationHelper.GetEnvOrDefaultString("DATABASE_ADDR", "127.0.0.1")
	DATABASE_ADDR     = GetEnvOrDefaultString("DATABASE_ADDR", "postgres")
	DATABASE_PORT     = GetEnvOrDefaultInt("DATABASE_PORT", 5432)
	DATABASE_SSL      = GetEnvOrDefaultBool("DATABASE_SSL", false)
	DATABASE_USERNAME = GetEnvOrDefaultString("DATABASE_USERNAME", "postgres")
	DATABASE_PASSWORD = GetEnvOrDefaultString("DATABASE_PASSWORD", "postgres")
	DATABASE_DATABASE = GetEnvOrDefaultString("DATABASE_DATABASE", "postgres")

	// Oauth
	AUTHORIZATION_OAUTH_KEY               = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_CLIENT_KEY", "")
	AUTHORIZATION_OAUTH_SECRET            = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_CLIENT_SECRET", "")
	AUTHORIZATION_OAUTH_CALLBACK_URL      = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_REDIRECT_URL", "http://web.localhost/api/v1/callback")
	AUTHORIZATION_OAUTH_AUTHORIZATION_URL = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_AUTHORIZATION_URL", "http://localhost:9000/application/o/authorize/")
	AUTHORIZATION_OAUTH_TOKEN_URL         = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_TOKEN_URL", "")
	AUTHORIZATION_OAUTH_USERINFO_URL      = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_USERINFO_URL", "")
	AUTHORIZATION_OAUTH_SCOPES            = GetEnvOrDefaultStringArray("AUTHORIZATION_OAUTH_SCOPES", []string{})
	AUTHORIZATION_OAUTH_LOGOUT_URL        = GetEnvOrDefaultString("AUTHORIZATION_OAUTH_LOGOUT_URL", "")

	// Certificates
	CERTIFICATE_IDENTITY_NAME                        = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_NAME", "uVulpos - My Application")
	CERTIFICATE_IDENTITY_ORGANIZATION                = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION", "The Innovators")
	CERTIFICATE_IDENTITY_ORGANIZATION_UNIT           = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION_UNIT", "Technical Innovation")
	CERTIFICATE_IDENTITY_ORGANIZATION_ADRESS         = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION_ADRESS", "Example Street 12a")
	CERTIFICATE_IDENTITY_ORGANIZATION_CITY           = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION_CITY", "Munich")
	CERTIFICATE_IDENTITY_ORGANIZATION_POSTAL_CODE    = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION_POSTAL_CODE", "12345")
	CERTIFICATE_IDENTITY_ORGANIZATION_POSTAL_STATE   = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION_POSTAL_STATE", "Bavaria")
	CERTIFICATE_IDENTITY_ORGANIZATION_POSTAL_COUNTRY = GetEnvOrDefaultString("CERTIFICATE_IDENTITY_ORGANIZATION_POSTAL_COUNTRY", "Germany")
)
