repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: goauthentik
    url: https://charts.goauthentik.io/
  - name: longhorn
    url: https://charts.longhorn.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: ingress
    chart: ingress-nginx/ingress-nginx
    namespace: ingress
    createNamespace: true
    values:
      - "./values/ingress-nginx.yaml"
  
  - name: longhorn
    chart: longhorn/longhorn
    version: 1.8.1
    namespace: longhorn
    createNamespace: true
    values:
      - "./values/storage-longhorn.yaml"
  
  - name: postgres
    chart: bitnami/postgresql
    namespace: postgres
    createNamespace: true
    needs:
      - longhorn/longhorn
    set:
      - name: global.storageClass
        value: longhorn
      - name: global.postgresql.auth.postgresPassword
        value: adminpw
      - name: global.postgresql.auth.username
        value: user
      - name: global.postgresql.auth.password
        value: userpassword
  
  # - name: authentik
  #   chart: goauthentik/authentik
  #   version: 2024.2.2
  #   namespace: identityprovider
  #   createNamespace: true
  #   needs:
  #     - ingress
  #     - longhorn
  #     - postgres
  #   values:
  #     - "./values/authentik-identity-provider.yaml"
  