name: "CI: Test Software"

on:
  push:

jobs:
  test-backend:
    runs-on: selfhost-hetzner
    # continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run backend tests
        if: ${{ always() }}
        run: make test-be
        env:
          APP_DB_ADDR: postgres
          APP_DB_PORT: 5432
          APP_DB_USERNAME: postgres
          APP_DB_PASSWORD: postgres
          APP_DB_DATABASENAME: postgres
          APP_DB_SSL_MODE: False

      - name: create gosec tmp dir
        run: mkdir -p /tmp/gosec

      - name: run security checks
        uses: securego/gosec@master
        with:
          args: "-no-fail -fmt html -out ./results.html ./services/backend/..."

      - uses: actions/upload-artifact@v4
        with:
          name: go-security-report.html
          path: ./results.html

      - name: Cleanup Workspace
        if: always()  
        run: |
          # Dateien oder Verzeichnisse löschen
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
