name: "License Check Audit"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  license-check-golang-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Golang | Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: Golang | Install License Checker
        run: go install github.com/google/go-licenses@latest

      - name: Golang | Run License Check
        run: make license-check-be

  license-check-npm-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM | Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 23.3.0
      - name: Install Dependencies
        run: (cd services/frontend ; npm install)

      - name: NPM | Install License Checker
        run: npm install -g license-checker

      - name: NPM | Run License Check
        run: make license-check-fe
